DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS comment;
DROP SEQUENCE IF EXISTS answer_id;
DROP SEQUENCE IF EXISTS user_id;
DROP SEQUENCE IF EXISTS question_id;
DROP SEQUENCE IF EXISTS comment_id;